import type {Metadata} from "next";
import {ICallbackLayoutProps} from "@/presentation/views/core/interfaces";
import {Root} from "@/presentation/router";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: ICallbackLayoutProps) {
  return <Root props={props}/>
}
